# Generated by Django 3.2.8 on 2022-05-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_ai', '0003_auto_20220518_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot_ai.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot_ai.data'),
        ),
    ]
