# Generated by Django 3.2.8 on 2022-05-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_ai', '0007_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Id',
        ),
        migrations.RenameModel(
            old_name='Dish',
            new_name='Menu',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot_ai.id'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot_ai.menu'),
        ),
    ]
