# Generated by Django 3.2.8 on 2022-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_ai', '0010_alter_plan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
