# Generated by Django 3.2.8 on 2022-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_ai', '0011_alter_plan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='市')),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='レストラン名')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリー')),
                ('cust_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': '対話',
                'verbose_name_plural': '対話リスト',
                'db_table': '対話データベース',
            },
        ),
    ]
